version: '3'

services:

  dishes:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mysqldb
    networks:
      popular-dishes-custom:
        ipv4_address: 172.40.1.2

  mysqldb:
    build: database/
    ports: 
      - '3306:3306'
    networks:
      popular-dishes-custom:
        ipv4_address: 172.40.1.1

networks:
    popular-dishes-custom:
        ipam:
            driver: default
            config:
                - subnet: 172.40.0.0/16